import metadata from './photo-metadata.json'

/**
 * Camera / EXIF metadata extracted from the original JPEG files.
 *
 * The data is generated by `npm run photos:metadata` (scripts/extract-metadata.mjs)
 * and keyed by the photo's public `src` path. Re-run that script whenever photos
 * are added or replaced.
 */
export interface PhotoExif {
  /** Camera make + model, e.g. "Canon EOS Rebel SL3". */
  camera?: string
  /** Lens model, e.g. "EF-S18-55mm f/4-5.6 IS STM". */
  lens?: string
  /** Capture date, pre-formatted, e.g. "May 23, 2024". */
  dateTaken?: string
  /** Pixel dimensions, e.g. "1200 × 800". */
  dimensions?: string
  /** Focal length, e.g. "22mm". */
  focalLength?: string
  /** Aperture, e.g. "f/4.5". */
  aperture?: string
  /** Shutter speed, e.g. "1/640s". */
  shutterSpeed?: string
  /** ISO sensitivity, e.g. 1600. */
  iso?: number
}

const photoMetadata = metadata as Record<string, PhotoExif>

/** Returns the EXIF metadata for a photo by its `src`, if any was extracted. */
export function getPhotoExif(src: string): PhotoExif | undefined {
  return photoMetadata[src]
}
